FROM node:25
WORKDIR /usr/server/app

COPY ./assets ./client/public/static/assets/
COPY ./frontend/package.json ./client/
COPY ./yarn.lock ./client/
COPY ./frontend ./client/
COPY ./config ./config
WORKDIR /usr/server/app/client
RUN yarn install --pure-lockfile
ENV NODE_ENV=production
RUN yarn build
CMD ["yarn", "start"]
EXPOSE 3000