FROM node:20
WORKDIR /usr/server/app

COPY ./frontend/package.json ./frontend/
COPY ./yarn.lock ./frontend/
# RUN yarn install --pure-lockfile
# COPY ./ .
# ENV NODE_ENV=production
# RUN yarn css:build
# RUN yarn build
# COPY ./../assets ./../public/static/assets/
# CMD ["yarn", "start"]
# EXPOSE 3000