FROM node:20
WORKDIR /usr/server/app
COPY ./backend/package.json ./backend
COPY ./yarn.lock ./backend
COPY ./backend ./backend
COPY ./config ./config
ENV NODE_ENV=production
WORKDIR /usr/server/app/backend
RUN yarn install --pure-lockfile
CMD ["yarn", "server:start"]
EXPOSE 4000