FROM node:20
WORKDIR /usr/server/app
COPY ./workers/package.json ./
COPY ./yarn.lock ./
RUN yarn install --pure-lockfile
COPY ./workers .
ENV NODE_ENV=production
CMD ["yarn", "server:start"]
EXPOSE 5000